% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Nov-2023 15:42:50
%  MATLAB version: 23.2.0.2409890 (R2023b) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('Lidar_Camera_calibration.mat');

tform = saveVarsMat.tform; % <1x1 rigidtform3d> unsupported class

clear saveVarsMat;
